//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Casher.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACTIONS
    {
        public decimal ID { get; set; }
        public string USERNAME { get; set; }
        public string DAT { get; set; }
        public string ACTION { get; set; }
        public string TIM { get; set; }
        public string VIEWNAME { get; set; }
        public string OPERATION { get; set; }
        public Nullable<decimal> PROGRAMUSERID { get; set; }
    }
}
