//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Casher.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class BLADIAINFO
    {
        public string NAMEAR { get; set; }
        public string NAMEEN { get; set; }
        public byte[] LOGO { get; set; }
        public string BOSS { get; set; }
        public string DEPARTNO { get; set; }
        public string SECTIONNO { get; set; }
        public string COMBOSS { get; set; }
        public string COMEMP { get; set; }
        public string SMSUSERNAME { get; set; }
        public string SMSPASSWORD { get; set; }
        public string SMSMESSAGE { get; set; }
        public decimal ID { get; set; }
    }
}
