//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Casher.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class COM_TREATMENT_COPY
    {
        public decimal ID { get; set; }
        public string DATCOPY { get; set; }
        public string ORGCOPY { get; set; }
        public Nullable<decimal> DETTOID { get; set; }
        public string DETTONAME { get; set; }
        public string OTHERDEP { get; set; }
        public string DETINCLUDES { get; set; }
        public string EMPNAME { get; set; }
        public string INDATE { get; set; }
        public string PROGRAMUSER { get; set; }
        public string COMPUTERUSER { get; set; }
        public string COMPUTERNAME { get; set; }
        public Nullable<decimal> MAINID { get; set; }
        public string EXPORTIMPORTTYPE { get; set; }
        public Nullable<decimal> ACTIVE { get; set; }
        public Nullable<decimal> PROGRAMUSERID { get; set; }
    }
}
