//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Casher.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class COM_LIST_IMPORT_REFER
    {
        public decimal ID { get; set; }
        public Nullable<decimal> MAINID { get; set; }
        public string NO { get; set; }
        public string DATE7ALA { get; set; }
        public string INCLUDES { get; set; }
        public Nullable<decimal> DEPPREPARID { get; set; }
        public string DEPPREPARNAME { get; set; }
        public Nullable<decimal> DEPTOID { get; set; }
        public string DEPTONAME { get; set; }
        public string EMPNAME { get; set; }
        public string INDATE { get; set; }
        public string PROGRAMUSER { get; set; }
        public string COMPUTERUSER { get; set; }
        public string COMPUTERNAME { get; set; }
        public Nullable<decimal> ESTELAM { get; set; }
        public string EGRAA { get; set; }
        public Nullable<decimal> ACTIVE { get; set; }
        public Nullable<decimal> PROGRAMUSERID { get; set; }
    }
}
