//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Casher.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class COM_EMPLOYEES_AUTHENTICATION
    {
        public decimal MAXID { get; set; }
        public decimal USERID { get; set; }
        public decimal VIEWID { get; set; }
        public Nullable<decimal> ENTER { get; set; }
        public Nullable<decimal> SAVE { get; set; }
        public Nullable<decimal> EDIT { get; set; }
        public Nullable<decimal> REMOVE { get; set; }
    }
}
