//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Casher.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class COM_EMPLOYEES
    {
        public decimal ID { get; set; }
        public string NO { get; set; }
        public string PASS { get; set; }
        public string NAME { get; set; }
        public Nullable<decimal> DEPID { get; set; }
        public string DEPNAME { get; set; }
        public Nullable<decimal> IMPORTANTTREATMENTS { get; set; }
        public Nullable<decimal> STOPEMP { get; set; }
        public Nullable<decimal> ADMIN { get; set; }
        public Nullable<decimal> MAJLESS { get; set; }
        public Nullable<decimal> MAJLESSADMIN { get; set; }
        public Nullable<decimal> ADMINEMP { get; set; }
        public Nullable<decimal> ROLE { get; set; }
        public string COMPUTERNAME { get; set; }
        public string INDATE { get; set; }
        public Nullable<decimal> PROGRAMUSERID { get; set; }
        public string COMPUTERUSER { get; set; }
        public string PROGRAMUSER { get; set; }
    }
}
