//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Casher.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class COM_PAYMENT_REGISTRATION
    {
        public Nullable<decimal> EXPORTID { get; set; }
        public Nullable<decimal> IMPORTID { get; set; }
        public string DATPAYMENT { get; set; }
        public Nullable<decimal> DEPID { get; set; }
        public string INDATE { get; set; }
        public string PROGRAMUSER { get; set; }
        public string COMPUTERUSER { get; set; }
        public string COMPUTERNAME { get; set; }
        public Nullable<decimal> EXPORTID1 { get; set; }
        public decimal ID { get; set; }
        public string TYPEEXPORTID { get; set; }
        public string TYPEIMPORTID { get; set; }
        public Nullable<decimal> PROGRAMUSERID { get; set; }
        public Nullable<decimal> ACTIVE { get; set; }
    }
}
