//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Casher.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class COM_EMPLOYEES_VIEWS
    {
        public decimal VIEWID { get; set; }
        public string VIEWNAME { get; set; }
        public string VIEWURL { get; set; }
    }
}
