//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Casher.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class COM_LIST_EXPORT
    {
        public decimal ID { get; set; }
        public Nullable<decimal> DEPARTMENTID { get; set; }
        public Nullable<decimal> NO { get; set; }
        public string DATEXPORT { get; set; }
        public Nullable<decimal> DEPARTMENTFROMID { get; set; }
        public string MAINSUBJECT { get; set; }
        public Nullable<decimal> TREATMENTTYPEID { get; set; }
        public string INCLUDES { get; set; }
        public string IMPORTANT { get; set; }
        public string ETHBATTYPE { get; set; }
        public string ETHBATNO { get; set; }
        public Nullable<decimal> DEPARTMENTTOID { get; set; }
        public string NOTES { get; set; }
        public Nullable<decimal> SUBJECTID { get; set; }
        public string REPLAY { get; set; }
        public string ACTION { get; set; }
        public string PREVTREATMENT { get; set; }
        public string PREVTREATMENTNO { get; set; }
        public string DATPREVTREATMENT { get; set; }
        public Nullable<decimal> BARCODEID { get; set; }
        public string INDATE { get; set; }
        public string PROGRAMUSER { get; set; }
        public string COMPUTERUSER { get; set; }
        public string COMPUTERNAME { get; set; }
        public string OTHERDEPARTMENTS { get; set; }
        public Nullable<decimal> YEAR { get; set; }
        public string RAFNO { get; set; }
        public string MALAFNO { get; set; }
        public byte[] PCTARCHIVE { get; set; }
        public Nullable<decimal> DEPARTMENTEXPORTNO { get; set; }
        public string INTERNALNO { get; set; }
        public string JAWALNO { get; set; }
        public string ALAKA { get; set; }
        public string CARDNO { get; set; }
        public Nullable<decimal> OLDID { get; set; }
        public Nullable<decimal> ADMIN { get; set; }
        public Nullable<decimal> MAJLESS { get; set; }
        public Nullable<decimal> MAJLESSADMIN { get; set; }
        public Nullable<decimal> ADMINEMP { get; set; }
        public Nullable<decimal> PROGRAMUSERID { get; set; }
        public Nullable<decimal> ACTIVE { get; set; }
        public string TASDEEDNO { get; set; }
        public string TASDEEDDATE { get; set; }
    }
}
