//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Casher.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class IMAGES_IMPORT
    {
        public decimal ID { get; set; }
        public Nullable<decimal> IMPORTID { get; set; }
        public string NAME { get; set; }
        public byte[] PICTURE { get; set; }
        public Nullable<decimal> ACTIVE { get; set; }
        public string UPLOADID { get; set; }
    }
}
