//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Casher.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice_Moshtary_Product
    {
        public int ID { get; set; }
        public int Invoice_Moshtary_Id { get; set; }
        public int Product_Id { get; set; }
        public int Amount { get; set; }
        public decimal Price { get; set; }
        public decimal Taxes { get; set; }
        public decimal TotalPrice { get; set; }
    
        public virtual Invoice_Moshtary Invoice_Moshtary { get; set; }
        public virtual Product Product { get; set; }
    }
}
