//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Casher.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice_Mowrid_Product
    {
        public int ID { get; set; }
        public int Invoice_Mowrid_Id { get; set; }
        public int Product_Id { get; set; }
        public int Store_id { get; set; }
        public System.DateTime Date_Poduction { get; set; }
        public string Date_Poduction_Hijri { get; set; }
        public System.DateTime Date_Expiration { get; set; }
        public string Date_Expiration_Hijri { get; set; }
        public int Amount_ByJumla { get; set; }
        public int Carton_Count { get; set; }
        public int Amount_ByUnit { get; set; }
        public decimal Price { get; set; }
        public Nullable<int> Rg3_Type { get; set; }
        public Nullable<int> Rg3_Amount { get; set; }
        public Nullable<System.DateTime> Rg3_Date_Poduction { get; set; }
        public string Rg3_Date_Poduction_Hijri { get; set; }
        public Nullable<System.DateTime> Rg3_Date_Expiration { get; set; }
        public string Rg3_Date_Expiration_Hijri { get; set; }
        public Nullable<decimal> Rg3_Price { get; set; }
    
        public virtual Invoice_Mowrid Invoice_Mowrid { get; set; }
        public virtual Product Product { get; set; }
        public virtual Store Store { get; set; }
    }
}
