//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Casher.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Moshtary
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Moshtary()
        {
            this.Invoice_Cancel = new HashSet<Invoice_Cancel>();
            this.Invoice_Moshtary = new HashSet<Invoice_Moshtary>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<int> Sejil { get; set; }
        public string JawalNO { get; set; }
        public string JawalNO2 { get; set; }
        public string Address { get; set; }
        public int Barcode { get; set; }
        public int User_ID { get; set; }
        public string ComputerName { get; set; }
        public string ComputerUser { get; set; }
        public System.DateTime InDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Invoice_Cancel> Invoice_Cancel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Invoice_Moshtary> Invoice_Moshtary { get; set; }
        public virtual User User { get; set; }
    }
}
