//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Casher.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.Invoice_Cancel_Product = new HashSet<Invoice_Cancel_Product>();
            this.Invoice_Moshtary_Product = new HashSet<Invoice_Moshtary_Product>();
            this.Invoice_Mowrid_Product = new HashSet<Invoice_Mowrid_Product>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public decimal Barcode { get; set; }
        public int Company_Id { get; set; }
        public decimal Price_Unit { get; set; }
        public decimal Price_Jumla { get; set; }
        public int Jumla_picesCount { get; set; }
        public decimal Taxes { get; set; }
        public Nullable<int> User_ID { get; set; }
        public string ComputerName { get; set; }
        public string ComputerUser { get; set; }
        public Nullable<System.DateTime> InDate { get; set; }
        public Nullable<decimal> Carton_Barcode { get; set; }
        public Nullable<int> Carton_ProCount { get; set; }
        public Nullable<System.DateTime> Date_Expiration { get; set; }
        public string Date_Expiration_Hijri { get; set; }
        public Nullable<decimal> Price_Mowrid { get; set; }
    
        public virtual Company Company { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Invoice_Cancel_Product> Invoice_Cancel_Product { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Invoice_Moshtary_Product> Invoice_Moshtary_Product { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Invoice_Mowrid_Product> Invoice_Mowrid_Product { get; set; }
        public virtual User User { get; set; }
    }
}
