//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Casher.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.Companies = new HashSet<Company>();
            this.Departments = new HashSet<Department>();
            this.Invoice_Cancel = new HashSet<Invoice_Cancel>();
            this.Invoice_Moshtary = new HashSet<Invoice_Moshtary>();
            this.Invoice_Moshtary_Sadad = new HashSet<Invoice_Moshtary_Sadad>();
            this.Invoice_Mowrid = new HashSet<Invoice_Mowrid>();
            this.Invoice_Mowrid_Sadad = new HashSet<Invoice_Mowrid_Sadad>();
            this.Moshtaries = new HashSet<Moshtary>();
            this.Mowrids = new HashSet<Mowrid>();
            this.Products = new HashSet<Product>();
            this.Sadad_Type = new HashSet<Sadad_Type>();
            this.Stores = new HashSet<Store>();
            this.UserActions = new HashSet<UserAction>();
            this.UserViews = new HashSet<UserView>();
        }
    
        public int ID { get; set; }
        public string NAME { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string EMAIL { get; set; }
        public int ROLE { get; set; }
        public string COMPUTERNAME { get; set; }
        public string COMPUTERUSER { get; set; }
        public string PROGRAMUSER { get; set; }
        public System.DateTime INDATE { get; set; }
        public bool STOPEMP { get; set; }
        public int PROGRAMUSERID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Company> Companies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Department> Departments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Invoice_Cancel> Invoice_Cancel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Invoice_Moshtary> Invoice_Moshtary { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Invoice_Moshtary_Sadad> Invoice_Moshtary_Sadad { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Invoice_Mowrid> Invoice_Mowrid { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Invoice_Mowrid_Sadad> Invoice_Mowrid_Sadad { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Moshtary> Moshtaries { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Mowrid> Mowrids { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product> Products { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sadad_Type> Sadad_Type { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Store> Stores { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserAction> UserActions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserView> UserViews { get; set; }
    }
}
